### ISSUE TITLE
DataContainer.cs does not have all needed Methodes to pass the test completely

### ISSUE THREAD

**Issue by NucsuM** [ccshane/ScriptDomTutorial#1]
Hello cris,

I also want to implement a t-sql parser with ScriptDom. I have a lot of scripts which I want to analyze. The Microsoft api-documentation does not contain examples :( . 
In my view, your blog is the biggest collection of examples about the usage of ScriptDom.

The "Joins"-Branch seams to have the latest code. So I created a Visual Studio Solution like in your Blog...

My Problem is that the DataContainer-Class does not have all the methodes to pass the tests[1]. The Method `AddTable` in `DataContainer.cs` accept one parameter, but the `SqlStatementsParser.cs` try to call this methode with two or three parameters[2].

Do you have a complete version of the `DataContainer.cs` in your local git-staging-area (that pass all the unittests) ? :)

Thanks 

Robert

[1]
![github1](https://cloud.githubusercontent.com/assets/7623214/17910439/1f1cd7da-6989-11e6-86b9-95aabf0304a3.JPG)

[2]
![github2](https://cloud.githubusercontent.com/assets/7623214/17910443/232133da-6989-11e6-8dee-c0cc71e89156.JPG)

**Comment by ccshane** [comment]
Thank you.  I have updated all of the code with new versions in the Joins branch.  This should now be working. I'm not sure what happened there.  I'll need to go through the other branches and clean them up as well.
